name: Create GitHub release
inputs:
  github_token:
    required: true
    type: string
  release_version:
    required: true
    type: string
runs:
  using: composite
  steps:
    - name: Check out repository
      uses: actions/checkout@v3

    - name: Generate changelog
      id: generate-changelog
      uses: mikepenz/release-changelog-builder-action@v3.7.0
      with:
        fromTag: ${{ steps.get-latest-release.outputs.release }}
        token: ${{ inputs.github_token }}

    - name: Create release
      uses: ncipollo/release-action@v1.12.0
      with:
        tag: ${{ inputs.release_version }}
        body: |
          # Changelog

          ${{ steps.generate-changelog.outputs.changelog }}

