version: "3.8"

services:
  api:
    build: .
    env_file: .env
    ports:
      - 8080:8080
    depends_on:
      - cache
      - database
    restart: always

  database:
    image : mongo:5.0
    command: mongod
    volumes:
      - .data/mongodb:/data/db
    ports:
      - 27017:27017
    restart: always

  cache:
    image : redis:alpine3.17
    command: redis-server
    volumes:
      - .data/redis:/data
    ports:
      - 6379:6379
    restart: always