version: "3.8"

services:
  api:
    env_file: .env
    ports:
      - 8080:8080
    depends_on:
      - database
    restart: always

  database:
    image : mongo:5.0
    command: mongod
    volumes:
      - .data/mongodb:/data/db
    ports:
      - 27017:27017
    restart: always