name: Increment release version
inputs:
  github_repository:
    required: true
    type: string
  github_token:
    required: true
    type: string
outputs:
  next_version:
    description: The incremented release version
    value: ${{ steps.increment-release-version.outputs.next-version }}
  changelog:
    description: Changelog of the changes between the current and the next versions
    value: ${{ steps.generate-changelog.outputs.changelog }}
runs:
  using: composite
  steps:
    - name: Check out repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Get latest release
      id: get-latest-release
      uses: pozetroninc/github-action-get-latest-release@v0.7.0
      with:
        repository: ${{ inputs.github_repository }}
        token: ${{ inputs.github_token }}

    - name: Increment release version
      id: increment-release-version
      uses: christian-draeger/increment-semantic-version@1.1.0
      with:
        current-version: ${{ steps.get-latest-release.outputs.release }}
        version-fragment: feature

    - name: Generate changelog
      id: generate-changelog
      uses: mikepenz/release-changelog-builder-action@v3.7.0
      with:
        fromTag: ${{ steps.get-latest-release.outputs.release }}
        toTag: ${{ steps.increment-release-version.outputs.next-version }}
        token: ${{ inputs.github_token }}

