// Code generated by mockery v2.20.0. DO NOT EDIT.

package mocks

import (
	aggregate "convercy/domain/aggregate"

	mock "github.com/stretchr/testify/mock"

	valueobject "convercy/domain/valueobject"
)

// CurrencyExchangeRatesCache is an autogenerated mock type for the CurrencyExchangeRatesCache type
type CurrencyExchangeRatesCache struct {
	mock.Mock
}

// GetCurrencyExchangeRates provides a mock function with given fields: code
func (_m *CurrencyExchangeRatesCache) GetCurrencyExchangeRates(code valueobject.CurrencyCode) (*aggregate.CurrencyExchangeRates, error) {
	ret := _m.Called(code)

	var r0 *aggregate.CurrencyExchangeRates
	var r1 error
	if rf, ok := ret.Get(0).(func(valueobject.CurrencyCode) (*aggregate.CurrencyExchangeRates, error)); ok {
		return rf(code)
	}
	if rf, ok := ret.Get(0).(func(valueobject.CurrencyCode) *aggregate.CurrencyExchangeRates); ok {
		r0 = rf(code)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*aggregate.CurrencyExchangeRates)
		}
	}

	if rf, ok := ret.Get(1).(func(valueobject.CurrencyCode) error); ok {
		r1 = rf(code)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SaveCurrencyExchangeRates provides a mock function with given fields: currencyExchangeRates
func (_m *CurrencyExchangeRatesCache) SaveCurrencyExchangeRates(currencyExchangeRates *aggregate.CurrencyExchangeRates) error {
	ret := _m.Called(currencyExchangeRates)

	var r0 error
	if rf, ok := ret.Get(0).(func(*aggregate.CurrencyExchangeRates) error); ok {
		r0 = rf(currencyExchangeRates)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type mockConstructorTestingTNewCurrencyExchangeRatesCache interface {
	mock.TestingT
	Cleanup(func())
}

// NewCurrencyExchangeRatesCache creates a new instance of CurrencyExchangeRatesCache. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewCurrencyExchangeRatesCache(t mockConstructorTestingTNewCurrencyExchangeRatesCache) *CurrencyExchangeRatesCache {
	mock := &CurrencyExchangeRatesCache{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
