name: Create and publish Docker image to DockerHub
on:
  workflow_call:
    inputs:
      version:
        required: true
        type: string
    secrets: inherit
jobs:
  build:
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: flavioltonon/convercy:latest
