# Warning, do not check out untrusted code with
# the pull_request_target event.
name: Label Pull Request
on:
  pull_request_target:
    types: [ opened, edited ]
jobs:
  label:
    runs-on: ubuntu-22.04
    steps:
      - uses: bcoe/conventional-release-labels@v1.3.0
        with:
          type_labels: '{"feat": "feature", "fix": "fix", "docs": "documentation", "test": "tests", "tests": "tests", "chore": "chore"}'
          ignored_types: '[]'