name: Development
on:
  push:
    branches: *
    branches-ignore: main
jobs:
  setup:
    runs-on: ubuntu-22.04
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

  test:
    steps:
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18

      - name: Install dependencies
        run: make install

      - name: Run tests
        run: make tests

