name: Development
on:
  push:
    branches: main
jobs:
  tests:
    environment: development
    runs-on: ubuntu-22.04
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18

      - name: Install dependencies
        run: make install

      - name: Run tests
        run: make tests

