name: Make release
on:
  push:
    branches: main
jobs:
  test:
    runs-on: ubuntu-22.04
    environment: production
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/run_tests
  build:
    runs-on: ubuntu-22.04
    needs: test
    environment: production
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/build_docker_image
        with:
          dockerhub_username: ${{ secrets.DOCKERHUB_USERNAME }}
          dockerhub_password: ${{ secrets.DOCKERHUB_TOKEN }}
          version: ${{ github.ref }}
  release:
    runs-on: ubuntu-22.04
    needs: build
    environment: production
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/create_github_release
        with:
          github_repository: ${{ github.repository }}
          github_token: ${{ github.token }}
