name: Make release
on:
  push:
    branches: feat/ci-release
jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/run_tests
  build:
    runs-on: ubuntu-22.04
    needs: test
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/build_docker_image
    secrets: inherit
  release:
    runs-on: ubuntu-22.04
    needs: build
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/create_github_release
    secrets: inherit
