name: Make release
on:
  push:
    branches: feat/ci-release
env:
  RUN_TESTS_LOCATION: ${{ github.repository }}/.github/workflows/run_tests.yaml@${{ github.sha }}
jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
      - name: Run tests
        uses: $RUN_TESTS_LOCATION
  build:
    runs-on: ubuntu-22.04
    needs: test
    steps:
      - name: Build image
        uses: ./.github/workflows/build_docker_image.yaml
  release:
    runs-on: ubuntu-22.04
    needs: build
    steps:
      - name: Create release
        uses: ./.github/workflows/create_github_release.yaml
