name: Make release
on:
  push:
    branches: feat/ci-release
jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/workflows/run_tests.yaml
  build:
    runs-on: ubuntu-22.04
    needs: test
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/workflows/build_docker_image.yaml
  release:
    runs-on: ubuntu-22.04
    needs: build
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/workflows/create_github_release.yaml
